<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gezo.Application\Gezo.Application.csproj" />
    <ProjectReference Include="..\Gezo.Domain\Gezo.Domain.csproj" />
  </ItemGroup>

</Project>
